# Generated by Django 5.2.8 on 2025-11-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='message_on_cake',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
