# Generated by Django 5.2.8 on 2025-12-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_place_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
