# Generated by Django 5.2.8 on 2025-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_custom_build_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
